/**
 * Loads the generated public content bundle. Generated by
 * `npm run build:shared && node scripts/build-content.mjs`, gitignored, and
 * guaranteed to carry no solution or hint text (asserted by the build script).
 */
import type { ContentManifest } from '@kirocrew-academy/shared';
import contentJson from '../generated/content.public.json';

export const content = contentJson as ContentManifest;

export function findWorld(worldId: string) {
  return content.worlds.find((w) => w.id === worldId);
}

export function findTopic(worldId: string, topicId: string) {
  return findWorld(worldId)?.topics.find((t) => t.id === topicId);
}

export function findChallenge(challengeId: string) {
  for (const world of content.worlds) {
    for (const topic of world.topics) {
      const challenge = topic.challenges.find((c) => c.id === challengeId);
      if (challenge) return { world, topic, challenge };
    }
  }
  return undefined;
}
