/**
 * Loads the generated client content. Generated by
 * `npm run build:shared && node scripts/build-content.mjs`, gitignored, and
 * guaranteed to carry no solution, hint or explanation text (asserted by the
 * build script).
 *
 * Two tiers on purpose. `contentIndex` is titles, lore and counts only, small
 * enough to sit in the entry chunk and enough for the world map, topic list,
 * progress and landing screens. A world's challenges are a separate chunk
 * fetched by `loadWorld` when the player actually enters that world, so nobody
 * downloads six locked worlds to read the first one.
 */
import type { ContentIndex, PublicWorld, WorldSummary } from '@kirocrew-academy/shared';
import indexJson from '../generated/content.index.json';

export const contentIndex = indexJson as ContentIndex;

export function findWorldSummary(worldId: string): WorldSummary | undefined {
  return contentIndex.worlds.find((w) => w.id === worldId);
}

export function findTopicSummary(worldId: string, topicId: string) {
  return findWorldSummary(worldId)?.topics.find((t) => t.id === topicId);
}

/**
 * Vite turns each glob entry into its own chunk, so this map holds loaders and
 * not data: nothing is fetched until one of them is called.
 */
const worldLoaders = import.meta.glob<{ default: PublicWorld }>('../generated/worlds/*.json');

const cache = new Map<string, PublicWorld>();
const inFlight = new Map<string, Promise<PublicWorld>>();

export function loadedWorld(worldId: string): PublicWorld | undefined {
  return cache.get(worldId);
}

export async function loadWorld(worldId: string): Promise<PublicWorld> {
  const cached = cache.get(worldId);
  if (cached) return cached;

  const pending = inFlight.get(worldId);
  if (pending) return pending;

  const key = Object.keys(worldLoaders).find((path) => path.endsWith(`/${worldId}.json`));
  if (!key) throw new Error(`unknown world: ${worldId}`);

  const promise = worldLoaders[key]()
    .then((mod) => {
      const world = mod.default;
      cache.set(worldId, world);
      inFlight.delete(worldId);
      return world;
    })
    .catch((err) => {
      inFlight.delete(worldId);
      throw err;
    });

  inFlight.set(worldId, promise);
  return promise;
}

export async function loadTopic(worldId: string, topicId: string) {
  const world = await loadWorld(worldId);
  const topic = world.topics.find((t) => t.id === topicId);
  return topic ? { world, topic } : undefined;
}

export async function loadChallenge(worldId: string, topicId: string, challengeId: string) {
  const found = await loadTopic(worldId, topicId);
  if (!found) return undefined;
  const challenge = found.topic.challenges.find((c) => c.id === challengeId);
  return challenge ? { ...found, challenge } : undefined;
}
